# STAR-CS Streamlit Dashboard (Multi-Aspect Reasoning View with Safety Regulatory Concerns)

import os
import time
import json
from datetime import datetime

import streamlit as st

# Path to the shared data directory where safety_report.json is written
DATA_DIR = os.path.expanduser('~/colcon_ws/src/star_cs_agent/data')
REPORT_FILE = os.path.join(DATA_DIR, 'safety_report.json')

# Basic page setup
st.set_page_config(page_title='STAR-CS Live Dashboard', layout='wide')
st.title('STAR-CS: Spatio-Temporal Agentic Reasoning for Construction Safety')

st.markdown(
    """
This dashboard shows the most recent safety reasoning event generated by the STAR-CS system.

- **Zone Entry events** focus on an agent entering a zone, the hazards in that zone, and co-located agents.
- **Risk Snapshot events** focus on the GRM-style risk topography, high-risk zones, and predicted interactions.
- **Safety Regulatory Concerns** combine OSHA/NIOSH reasoning with physics-based, predictive analysis.
"""
)

# We use a placeholder so we can refresh the whole layout every few seconds
placeholder = st.empty()

while True:
    if os.path.exists(REPORT_FILE):
        try:
            with open(REPORT_FILE, 'r') as f:
                report = json.load(f)
        except Exception:
            report = None

        if report:
            with placeholder.container():
                # Basic metadata
                event_type = report.get('event_type', 'Unknown Event')
                ts = report.get('timestamp')
                ts_human = (
                    datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
                    if isinstance(ts, (int, float)) else 'N/A'
                )

                # Header row: event type + time + short description
                col0, col1 = st.columns([1, 3])
                with col0:
                    if event_type == 'Zone Entry':
                        st.success(f'Event: {event_type}')
                    elif event_type == 'Risk Snapshot':
                        st.warning(f'Event: {event_type}')
                    else:
                        st.info(f'Event: {event_type}')
                    st.caption(f'Last update: {ts_human}')
                with col1:
                    st.markdown('**Event Summary**')
                    st.write(report.get('details', 'No details available.'))

                st.markdown('---')

                # Row 1: Situation Overview + Risk Zones & Interactions
                c1, c2 = st.columns(2)
                with c1:
                    st.subheader('Situation Overview')
                    st.markdown(report.get('situation_overview', 'No overview available.'))
                with c2:
                    st.subheader('Risk Zones & Predicted Interactions')
                    st.info(
                        report.get(
                            'risk_zones_and_interactions',
                            'No risk zones or interactions reported.'
                        )
                    )

                st.markdown('---')

                # Row 2: Safety Regulatory Concerns + Recommendations
                c3, c4 = st.columns(2)
                with c3:
                    st.subheader('Safety Regulatory Concerns')
                    st.markdown(
                        report.get(
                            'safety_regulatory_concerns',
                            'No safety regulatory concerns reported yet.'
                        )
                    )
                with c4:
                    st.subheader('Actionable Recommendations')
                    st.warning(
                        report.get(
                            'actionable_recommendations',
                            'No recommendations yet.'
                        )
                    )

    else:
        # If no report yet, show a waiting message
        with placeholder.container():
            st.info('System is running… waiting for the first safety reasoning event.')

    # Poll every 2 seconds
    time.sleep(2)
