# STAR-CS Streamlit Dashboard
# - Live view of latest STAR-CS reasoning event
# - Sidebar chat to talk with the safety agent over long-term memory

import os
import time
import json
from datetime import datetime

import streamlit as st
import requests

# Path to the shared data directory where safety_report.json is written
DATA_DIR = os.path.expanduser('~/colcon_ws/src/star_cs_agent/data')
REPORT_FILE = os.path.join(DATA_DIR, 'safety_report.json')

# Reasoning API (Flask) URL
REASONING_API_URL = "http://127.0.0.1:5001"

# Basic page setup
st.set_page_config(page_title='STAR-CS Live Dashboard', layout='wide')
st.title('STAR-CS: Spatio-Temporal Agentic Reasoning for Construction Safety')

st.markdown(
    """
This dashboard shows the most recent safety reasoning event generated by the STAR-CS system,
and also lets you **chat with the STAR-CS safety agent** using its long-term memory.

- **Zone Entry events** focus on an agent entering a zone, the hazards in that zone, and co-located agents.
- **Risk Snapshot events** focus on the GRM-style risk topography, high-risk zones, and predicted interactions.
- **Safety Regulatory Concerns** combine OSHA/NIOSH reasoning with physics-based, predictive analysis.
"""
)

# ---------------- Sidebar Chat with Safety Agent ----------------

st.sidebar.header("Chat with Safety Agent")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# Display chat history
for role, text in st.session_state.chat_history:
    with st.sidebar.chat_message(role):
        st.markdown(text)

# Chat input
user_input = st.sidebar.chat_input("Ask about site safety, zones, or trends...")
if user_input:
    # Show user message
    st.session_state.chat_history.append(("user", user_input))
    with st.sidebar.chat_message("user"):
        st.markdown(user_input)

    # Query the /chat endpoint
    try:
        resp = requests.post(
            f"{REASONING_API_URL}/chat",
            json={"user_query": user_input},
            timeout=30,
        )
        if resp.status_code == 200:
            data = resp.json()
            answer = data.get("answer", "No answer received from safety agent.")
        else:
            answer = f"Error {resp.status_code} from safety agent: {resp.text}"
    except Exception as e:
        answer = f"Error contacting safety agent: {e}"

    st.session_state.chat_history.append(("assistant", answer))
    with st.sidebar.chat_message("assistant"):
        st.markdown(answer)

# ---------------- Main Live Event View ----------------

placeholder = st.empty()

while True:
    if os.path.exists(REPORT_FILE):
        try:
            with open(REPORT_FILE, 'r') as f:
                report = json.load(f)
        except Exception:
            report = None

        if report:
            with placeholder.container():
                # Basic metadata
                event_type = report.get('event_type', 'Unknown Event')
                ts = report.get('timestamp')
                ts_human = (
                    datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
                    if isinstance(ts, (int, float)) else 'N/A'
                )

                # Header row: event type + time + short description
                col0, col1 = st.columns([1, 3])
                with col0:
                    if event_type == 'Zone Entry':
                        st.success(f'Event: {event_type}')
                    elif event_type == 'Risk Snapshot':
                        st.warning(f'Event: {event_type}')
                    else:
                        st.info(f'Event: {event_type}')
                    st.caption(f'Last update: {ts_human}')
                with col1:
                    st.markdown('**Event Summary**')
                    st.write(report.get('details', 'No details available.'))

                st.markdown('---')

                # Row 1: Situation Overview + Risk Zones & Interactions
                c1, c2 = st.columns(2)
                with c1:
                    st.subheader('Situation Overview')
                    st.markdown(report.get('situation_overview', 'No overview available.'))
                with c2:
                    st.subheader('Risk Zones & Predicted Interactions')
                    st.info(
                        report.get(
                            'risk_zones_and_interactions',
                            'No risk zones or interactions reported.'
                        )
                    )

                st.markdown('---')

                # Row 2: Safety Regulatory Concerns + Recommendations
                c3, c4 = st.columns(2)
                with c3:
                    st.subheader('Safety Regulatory Concerns')
                    st.markdown(
                        report.get(
                            'safety_regulatory_concerns',
                            'No safety regulatory concerns reported yet.'
                        )
                    )
                with c4:
                    st.subheader('Actionable Recommendations')
                    st.warning(
                        report.get(
                            'actionable_recommendations',
                            'No recommendations yet.'
                        )
                    )

    else:
        # If no report yet, show a waiting message
        with placeholder.container():
            st.info('System is running… waiting for the first safety reasoning event.')

    # Poll every 2 seconds
    time.sleep(2)
